"""Regenerates the game enum tables used by both the Lua mod and the desktop app.

Source of truth: ExtIdeHelpers.lua, which the Script Extender generates from the
game's own enumerations and property maps (it is shipped inside the extender and
mirrored in the ositools repository).

Usage:
    python tools/generate_enums.py <path-to-ExtIdeHelpers.lua>
"""

import json
import os
import re
import sys

ATTRIBUTES = ["Strength", "Finesse", "Intelligence", "Constitution", "Memory", "Wits"]

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LUA_OUT = os.path.join(ROOT, "mod", "Story", "RawFiles", "Lua", "EocTrainer", "Enums.lua")
CS_OUT = os.path.join(ROOT, "src", "EocTrainer", "Core", "GameEnums.g.cs")
REPORT = os.path.join(ROOT, "docs", "api", "enum-report.txt")


def parse(path):
    text = open(path, encoding="utf-8", errors="replace").read()
    lines = text.split("\n")

    def alias(name):
        match = re.search(r"--- @alias %s string\|(.*)" % name, text)
        if not match:
            return []
        return sorted(set(re.findall(r'"([^"]+)"', match.group(1))))

    # The character stat sheet class lists every readable field.
    index = next(i for i, l in enumerate(lines) if "BaseWarriorLore" in l)
    start = index
    while start > 0 and not lines[start].lstrip().startswith("--- @class"):
        start -= 1
    end = index
    while end < len(lines) and not (lines[end].lstrip().startswith("--- @class") and end > index):
        end += 1
    fields = re.findall(r"--- @field (\w+) (\w+)", "\n".join(lines[start:end]))
    field_names = {name for name, _ in fields}

    return {
        "header": lines[start].strip(),
        "fields": field_names,
        "ability_enum": alias("StatsAbilityType"),
        "talent_enum": alias("StatsTalentType"),
    }


def main():
    source = sys.argv[1] if len(sys.argv) > 1 else None
    if not source or not os.path.isfile(source):
        print("usage: python tools/generate_enums.py <ExtIdeHelpers.lua>")
        return 1

    data = parse(source)

    abilities = sorted(n for n in data["ability_enum"] if n in data["fields"])
    talents = sorted(n for n in data["talent_enum"] if ("TALENT_" + n) in data["fields"])

    report = []
    report.append("source            : %s" % source)
    report.append("stat sheet class  : %s" % data["header"])
    report.append("attributes        : %d" % len(ATTRIBUTES))
    report.append("abilities         : %d (enum %d, readable %d)"
                  % (len(abilities), len(data["ability_enum"]), len(abilities)))
    report.append("talents           : %d (enum %d, readable %d)"
                  % (len(talents), len(data["talent_enum"]), len(talents)))
    report.append("")
    report.append("ability enum entries without a readable stat field:")
    report.append("  " + ", ".join(sorted(set(data["ability_enum"]) - set(abilities))))
    report.append("")
    report.append("talent enum entries without a readable stat field:")
    report.append("  " + ", ".join(sorted(set(data["talent_enum"]) - set(talents))))
    report.append("")
    report.append("abilities: " + ", ".join(abilities))
    report.append("")
    report.append("talents: " + ", ".join(talents))
    open(REPORT, "w", encoding="utf-8").write("\n".join(report) + "\n")

    write_lua(ATTRIBUTES, abilities, talents)
    write_csharp(ATTRIBUTES, abilities, talents)
    print("\n".join(report[:8]))
    return 0


def write_lua(attributes, abilities, talents):
    def block(name, values):
        body = ",\n".join('    "%s"' % v for v in values)
        return "EocTrainer.%s = {\n%s,\n}\n" % (name, body)

    text = (
        "-- Generated by tools/generate_enums.py - do not edit by hand.\n"
        "-- Names come from the game's own enumerations, so they are exactly what\n"
        "-- the extender's NRD_PlayerSetBase* calls expect.\n\n"
        "EocTrainer = EocTrainer or {}\n\n"
        + block("ATTRIBUTES", attributes)
        + "\n"
        + block("ABILITIES", abilities)
        + "\n"
        + block("TALENTS", talents)
    )
    os.makedirs(os.path.dirname(LUA_OUT), exist_ok=True)
    open(LUA_OUT, "w", encoding="utf-8", newline="\n").write(text)


def write_csharp(attributes, abilities, talents):
    def block(name, values, comment):
        body = "\n".join('        "%s",' % v for v in values)
        return "    /// <summary>%s</summary>\n    public static readonly string[] %s =\n    {\n%s\n    };\n" % (
            comment, name, body)

    text = (
        "// <auto-generated>\n"
        "// Generated by tools/generate_enums.py - do not edit by hand.\n"
        "// </auto-generated>\n\n"
        "namespace EocTrainer.Core;\n\n"
        "public static partial class GameEnums\n"
        "{\n"
        + block("Attributes", attributes, "The six attributes of the character sheet.")
        + "\n"
        + block("Abilities", abilities, "Ability enum values (combat and civil abilities).")
        + "\n"
        + block("Talents", talents, "TalentType enum values.")
        + "}\n"
    )
    os.makedirs(os.path.dirname(CS_OUT), exist_ok=True)
    open(CS_OUT, "w", encoding="utf-8", newline="\n").write(text)


if __name__ == "__main__":
    sys.exit(main())
